<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginProcesoTable extends Doctrine_Table {

    public function findByList($ids = array()) {
        $q = $this->createQuery('p');
        $q->andWhereIn('p.id', $ids);
        return $q->execute();
    }
}