<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginProceso extends BaseProceso {
    // Dom xpdl
    var $xml = null;

    public function __toString() {
        return $this->getNombre();
    }

    public function getNombreConPaquete() {
        return $this->getRelPaquete().' -- '.$this->getNombre();
    }

    /**
     * Inserta un esqueleto proceso xpdl en un paquete xpdl
     * @return unknown_type
     */
    public function generate() {
        $pack = Doctrine::getTable('Paquete')->find($this->getRelPaquete());
        $macro = $pack->getMacro();
        if(!$macro) {
            throw new sfException(sprintf('No puede generar un proceso dentro de un Macro "%s"', $pack->getNombre()));
        }

        $arguments['application'] = $macro->getXpdlId();
        $arguments['module'] = $pack->getXpdlId();
        $arguments['process_id'] = $this->getXpdlId();
        $arguments['process_name'] = $this->getNombre();
        $arguments['process_display_name'] = $this->getNombre();
        $options = array();
        $app = new psdfGenerateProcess();
        $app->execute($arguments, $options);
    }

    public function parseImplementationName() {
        $name = strtolower( str_replace(' ', '_', $this->getNombre()) );
        return $name;
    }
    
    public function getInfoSymfony( ) {
        $info = array(
                'application' => $this->getPaquete()->getMacro()->parseImplementationName(),
                'module' => $this->getPaquete()->parseImplementationName(),
                'action' => $this->getPaquete()->parseActivityImplementationName($this->getNombre(), '', 'StartEvent'),
            );

        return $info;
    }

}