<?php

/**
 * PluginMacro
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginMacro extends BaseMacro {

    public function __toString() {
        return $this->getNombre();
    }

    /**
     * Valida si el macro ya está implementado.
     * Esta validacion es directamente sobre el directorio.
     * Un Macro se implementa como aplicativo symfony mediante el Nombre.
     *
     * @return boolean
     */
    public function isImplemented() {
        // Es un macro, valido si tiene su aplicativo creado
        $app = $this->parseImplementationName();
        $appDir = sfConfig::get('sf_apps_dir').'/'.$app;
        if (is_dir($appDir)) {
            return true;
        }
        return false;
    }

    /**
     * Implementa el macro como un aplicativo symfony
     */
    public function implement() {
        UtilPsdf::runTask('psdfGenerateMacroTask', array($this->parseImplementationName()));
    }

    public function parseImplementationName() {
        $name = strtolower( str_replace(' ', '_', $this->getNombre()) );
        return $name;
    }
}

?>