<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginEstadoFlow extends BaseEstadoFlow
{
  // Constantes idem registros tabla
  const INACTIVO = 1;
  const ACTIVO = 2;
  const SUSPENDIDO = 3;
  const COMPLETADO = 4;
  const TERMINADO = 5;
}