<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginOrganizacion extends BaseOrganizacion
{
  public function __toString(){
    return $this->getNombre();
  }    
}