<?php

/**
 * PluginProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginProyecto extends BaseProyecto
{

  /**
   * Construccion de un workspace con los paquetes del proyecto
   * @param $pPath       Ruta destino del workspace (debe tener permisos de escritura)
   * @return unknown_type
   */
  public function generateWorkspace( $pPath )
  {
    // Genero estructura de directorios
    $arguments['path'] = $pPath;
    $arguments['packages'] = $this->getPaquetesAExportar();
    $options = array();

    $ws = new psdfGenerateWorkspace();
    $ws->execute($arguments, $options);
  }

  /**
   * Recupero una lista con los nombres, xpdl y macro de paquetes a exportar para
   * trabajarlo localmente.
   * Aquí deberían agregarse los filtros necesarios para no traer todos.
   * @return array Lista de paquetes (nombre y xpdl)
   */
  public function getPaquetesAExportar()
  {
    $packs = Doctrine_Core::getTable('Paquete')->getPaquetesByProyecto($this->getId());
    $list=array();
    $key=-1;
    foreach( $packs as $pack)
    {
        $key++;
        $list[$key]['name'] = $pack->getNombre();
        $list[$key]['xpdl'] = $pack->getXpdl();
        $list[$key]['macro'] = $pack->getNombreMacroPaquete();
    }
    return $list;
  }

public function processWorkspace( $pPath, $pFiles ) {
    $noimp = array();
    foreach( $pFiles as $file ) {
        $ok = false;

        // Intento determinar Ids de paquete y Macro a partir de atributos del xpdl a importar
        $xpdlId = UtilXpdl::getFileXpdlId($pPath.'/proyecto/Process Packages/'.$file);
        $xpdlName = UtilXpdl::getFileXpdlId($pPath.'/proyecto/Process Packages/'.$file);
        $xpdlMacroId = UtilXpdl::getFileXpdlMacroId($pPath.'/proyecto/Process Packages/'.$file);
        $xpdlMacroName = UtilXpdl::getFileXpdlMacroName($file);
        $content = file_get_contents($pPath.'/proyecto/Process Packages/'.$file);

        // Intento recuperar Paquete si ya estuviese almacenado
        $pack = Doctrine::getTable('Paquete')->find(substr($xpdlId,1)>0?substr($xpdlId,1):0); // Saco el guion bajo

        // Intento recuperar Macro si ya estuviese almacenado. Lo determino por:
        //  1- el macro Id como atributo extendido en el xpdl
        //  2- el nombre de la subcarpeta que contiene el xpdl
        // (Prevalece 1 sobre 2)
        if( $xpdlMacroId>0 ) {
            $macro = Doctrine::getTable('Paquete')->find($xpdlMacroId);
        }
        else {
            $macro = Doctrine::getTable('Paquete')->findByNombre($xpdlMacroName);
            if( count($macro)>0 ) {
                $macro = $macro[0];
            }
            else {
                $macro = false;
            }
        }

        if( !$macro ) {
            $macro = new Paquete();
            $macro->setNombre($xpdlMacroName);
            $macro->save();
        }

        // Actualizo el nombre si fuese cambiado
        if( $macro->getNombre()!=$xpdlMacroName ) {
            $macro->setNombre($xpdlMacroName);
            $macro->save();
        }

        if( !$pack ) {
            $pack = new Paquete();
            $pack->setNombre($xpdlName);
            $pack->setXpdl($content);
            $pack->setRelPaquete($macro->getId());
            $pack->save();
        }

        if( $pack->getRelPaquete()==$macro->getId() ) {
            // Cumple los requisitos de sincronizacion. Paso a actualizarlo
            $pack->setXpdl($content);
            $pack->save();
            $ok = true;
        }
        else {
            $err['file'] = $file;
            $err['error'] = 'El Macro Id '.$xpdlId.' informado no coincide con el ya vinculado al paquete';
            $noimp[] = $err;
        }
    }
    return $noimp;
}


}