<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginPicture extends BasePicture
{
  public function __toString(){
    return $this->getNombre();
  }  
	
}