<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Unidadorg', 'psdf');

/**
 * BaseUnidadorg
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $rel_organizacion
 * @property Organizacion $Organizacion
 * 
 * @method string       getNombre()           Returns the current record's "nombre" value
 * @method integer      getRelOrganizacion()  Returns the current record's "rel_organizacion" value
 * @method Organizacion getOrganizacion()     Returns the current record's "Organizacion" value
 * @method Unidadorg    setNombre()           Sets the current record's "nombre" value
 * @method Unidadorg    setRelOrganizacion()  Sets the current record's "rel_organizacion" value
 * @method Unidadorg    setOrganizacion()     Sets the current record's "Organizacion" value
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUnidadorg extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdforg.unidadorg');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('rel_organizacion', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organizacion', array(
             'local' => 'rel_organizacion',
             'foreign' => 'id'));
    }
}