<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstadoFlow', 'psdf');

/**
 * BaseEstadoFlow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * 
 * @method string     getNombre()      Returns the current record's "nombre" value
 * @method string     getDescripcion() Returns the current record's "descripcion" value
 * @method EstadoFlow setNombre()      Sets the current record's "nombre" value
 * @method EstadoFlow setDescripcion() Sets the current record's "descripcion" value
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEstadoFlow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdfwf.estado_flow');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('descripcion', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}