<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Picture', 'psdf');

/**
 * BasePicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $rel_paquete
 * @property Paquete $Paquete
 * @property Doctrine_Collection $Coordenadas
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method integer             getRelPaquete()  Returns the current record's "rel_paquete" value
 * @method Paquete             getPaquete()     Returns the current record's "Paquete" value
 * @method Doctrine_Collection getCoordenadas() Returns the current record's "Coordenadas" collection
 * @method Picture             setNombre()      Sets the current record's "nombre" value
 * @method Picture             setRelPaquete()  Sets the current record's "rel_paquete" value
 * @method Picture             setPaquete()     Sets the current record's "Paquete" value
 * @method Picture             setCoordenadas() Sets the current record's "Coordenadas" collection
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePicture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdfwf.picture');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('rel_paquete', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paquete', array(
             'local' => 'rel_paquete',
             'foreign' => 'id'));

        $this->hasMany('Coordenada as Coordenadas', array(
             'local' => 'id',
             'foreign' => 'rel_picture'));
    }
}