<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Activity', 'psdf');

/**
 * BaseActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdfwf.activity');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}