<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Flow', 'psdf');

/**
 * BaseFlow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $datafields
 * @property integer $rel_estado
 * @property integer $rel_proceso
 * @property Proceso $Proceso
 * @property Doctrine_Collection $FlowDet1
 * 
 * @method string              getDatafields()  Returns the current record's "datafields" value
 * @method integer             getRelEstado()   Returns the current record's "rel_estado" value
 * @method integer             getRelProceso()  Returns the current record's "rel_proceso" value
 * @method Proceso             getProceso()     Returns the current record's "Proceso" value
 * @method Doctrine_Collection getFlowDet1()    Returns the current record's "FlowDet1" collection
 * @method Flow                setDatafields()  Sets the current record's "datafields" value
 * @method Flow                setRelEstado()   Sets the current record's "rel_estado" value
 * @method Flow                setRelProceso()  Sets the current record's "rel_proceso" value
 * @method Flow                setProceso()     Sets the current record's "Proceso" value
 * @method Flow                setFlowDet1()    Sets the current record's "FlowDet1" collection
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFlow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdfwf.flow');
        $this->hasColumn('datafields', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('rel_estado', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rel_proceso', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Proceso', array(
             'local' => 'rel_proceso',
             'foreign' => 'id'));

        $this->hasMany('FlowDet as FlowDet1', array(
             'local' => 'id',
             'foreign' => 'rel_flow'));
    }
}