<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FlowDet', 'psdf');

/**
 * BaseFlowDet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $activity_id
 * @property integer $rel_estado
 * @property integer $rel_flow
 * @property integer $rel_usuario
 * @property time $tstart
 * @property time $tend
 * @property Flow $Flow
 * @property Usuario $Usuario
 * 
 * @method string  getActivityId()  Returns the current record's "activity_id" value
 * @method integer getRelEstado()   Returns the current record's "rel_estado" value
 * @method integer getRelFlow()     Returns the current record's "rel_flow" value
 * @method integer getRelUsuario()  Returns the current record's "rel_usuario" value
 * @method time    getTstart()      Returns the current record's "tstart" value
 * @method time    getTend()        Returns the current record's "tend" value
 * @method Flow    getFlow()        Returns the current record's "Flow" value
 * @method Usuario getUsuario()     Returns the current record's "Usuario" value
 * @method FlowDet setActivityId()  Sets the current record's "activity_id" value
 * @method FlowDet setRelEstado()   Sets the current record's "rel_estado" value
 * @method FlowDet setRelFlow()     Sets the current record's "rel_flow" value
 * @method FlowDet setRelUsuario()  Sets the current record's "rel_usuario" value
 * @method FlowDet setTstart()      Sets the current record's "tstart" value
 * @method FlowDet setTend()        Sets the current record's "tend" value
 * @method FlowDet setFlow()        Sets the current record's "Flow" value
 * @method FlowDet setUsuario()     Sets the current record's "Usuario" value
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFlowDet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdfwf.flow_det');
        $this->hasColumn('activity_id', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('rel_estado', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rel_flow', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rel_usuario', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tstart', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('tend', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Flow', array(
             'local' => 'rel_flow',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'rel_usuario',
             'foreign' => 'id'));
    }
}