<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Organizacion', 'psdf');

/**
 * BaseOrganizacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $Unidadorgs
 * @property Doctrine_Collection $Paquetes
 * 
 * @method string              getNombre()     Returns the current record's "nombre" value
 * @method Doctrine_Collection getUnidadorgs() Returns the current record's "Unidadorgs" collection
 * @method Doctrine_Collection getPaquetes()   Returns the current record's "Paquetes" collection
 * @method Organizacion        setNombre()     Sets the current record's "nombre" value
 * @method Organizacion        setUnidadorgs() Sets the current record's "Unidadorgs" collection
 * @method Organizacion        setPaquetes()   Sets the current record's "Paquetes" collection
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOrganizacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdforg.organizacion');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Unidadorg as Unidadorgs', array(
             'local' => 'id',
             'foreign' => 'rel_organizacion'));

        $this->hasMany('Paquete as Paquetes', array(
             'local' => 'id',
             'foreign' => 'rel_organizacion'));
    }
}