<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Coordenada', 'psdf');

/**
 * BaseCoordenada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property integer $pxtop
 * @property integer $pxleft
 * @property integer $rel_picture
 * @property integer $rel_proceso
 * @property Picture $Picture
 * @property Proceso $Proceso
 * 
 * @method string     getNombre()      Returns the current record's "nombre" value
 * @method integer    getPxtop()       Returns the current record's "pxtop" value
 * @method integer    getPxleft()      Returns the current record's "pxleft" value
 * @method integer    getRelPicture()  Returns the current record's "rel_picture" value
 * @method integer    getRelProceso()  Returns the current record's "rel_proceso" value
 * @method Picture    getPicture()     Returns the current record's "Picture" value
 * @method Proceso    getProceso()     Returns the current record's "Proceso" value
 * @method Coordenada setNombre()      Sets the current record's "nombre" value
 * @method Coordenada setPxtop()       Sets the current record's "pxtop" value
 * @method Coordenada setPxleft()      Sets the current record's "pxleft" value
 * @method Coordenada setRelPicture()  Sets the current record's "rel_picture" value
 * @method Coordenada setRelProceso()  Sets the current record's "rel_proceso" value
 * @method Coordenada setPicture()     Sets the current record's "Picture" value
 * @method Coordenada setProceso()     Sets the current record's "Proceso" value
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCoordenada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdfwf.coordenada');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('pxtop', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pxleft', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rel_picture', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rel_proceso', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Picture', array(
             'local' => 'rel_picture',
             'foreign' => 'id'));

        $this->hasOne('Proceso', array(
             'local' => 'rel_proceso',
             'foreign' => 'id'));
    }
}