<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'psdf');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $pass
 * @property Doctrine_Collection $FlowDet2
 * 
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method string              getPass()     Returns the current record's "pass" value
 * @method Doctrine_Collection getFlowDet2() Returns the current record's "FlowDet2" collection
 * @method Usuario             setNombre()   Sets the current record's "nombre" value
 * @method Usuario             setPass()     Sets the current record's "pass" value
 * @method Usuario             setFlowDet2() Sets the current record's "FlowDet2" collection
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdforg.usuario');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('pass', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FlowDet as FlowDet2', array(
             'local' => 'id',
             'foreign' => 'rel_usuario'));
    }
}