<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Paquete', 'psdf');

/**
 * BasePaquete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $xpdl
 * @property integer $rel_organizacion
 * @property integer $rel_paquete
 * @property Organizacion $Organizacion
 * @property Paquete $Paquete
 * @property Doctrine_Collection $Paquetes2
 * @property Doctrine_Collection $Procesos
 * @property Doctrine_Collection $Pictures
 * 
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getXpdl()             Returns the current record's "xpdl" value
 * @method integer             getRelOrganizacion()  Returns the current record's "rel_organizacion" value
 * @method integer             getRelPaquete()       Returns the current record's "rel_paquete" value
 * @method Organizacion        getOrganizacion()     Returns the current record's "Organizacion" value
 * @method Paquete             getPaquete()          Returns the current record's "Paquete" value
 * @method Doctrine_Collection getPaquetes2()        Returns the current record's "Paquetes2" collection
 * @method Doctrine_Collection getProcesos()         Returns the current record's "Procesos" collection
 * @method Doctrine_Collection getPictures()         Returns the current record's "Pictures" collection
 * @method Paquete             setNombre()           Sets the current record's "nombre" value
 * @method Paquete             setXpdl()             Sets the current record's "xpdl" value
 * @method Paquete             setRelOrganizacion()  Sets the current record's "rel_organizacion" value
 * @method Paquete             setRelPaquete()       Sets the current record's "rel_paquete" value
 * @method Paquete             setOrganizacion()     Sets the current record's "Organizacion" value
 * @method Paquete             setPaquete()          Sets the current record's "Paquete" value
 * @method Paquete             setPaquetes2()        Sets the current record's "Paquetes2" collection
 * @method Paquete             setProcesos()         Sets the current record's "Procesos" collection
 * @method Paquete             setPictures()         Sets the current record's "Pictures" collection
 * 
 * @package    psdf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePaquete extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('psdfwf.paquete');
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '30',
             ));
        $this->hasColumn('xpdl', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('rel_organizacion', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rel_paquete', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organizacion', array(
             'local' => 'rel_organizacion',
             'foreign' => 'id'));

        $this->hasOne('Paquete', array(
             'local' => 'rel_paquete',
             'foreign' => 'id'));

        $this->hasMany('Paquete as Paquetes2', array(
             'local' => 'id',
             'foreign' => 'rel_paquete'));

        $this->hasMany('Proceso as Procesos', array(
             'local' => 'id',
             'foreign' => 'rel_paquete'));

        $this->hasMany('Picture as Pictures', array(
             'local' => 'id',
             'foreign' => 'rel_paquete'));
    }
}